#!/usr/bin/env bash
#
# sync-prices.sh — sync model pricing from models.dev into the repo.
#
# Downloads https://models.dev/api.json into internal/catalog/models-dev.json
# (the file the gateway //go:embeds at build time for offline pricing). Run it
# periodically to pick up new models and price changes; commit the result so
# pricing updates are tracked in git history.
#
# Usage:
#   ./scripts/sync-prices.sh             # download + verify + diff summary
#   ./scripts/sync-prices.sh --commit    # also stage + commit the update
#
# Exit codes: 0 ok (or nothing to commit), 1 download/verify failure.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_URL="https://models.dev/api.json"
DEST="$REPO_ROOT/internal/catalog/models-dev.json"
TMP="$(mktemp -t prices.XXXXXX.json)"
trap 'rm -f "$TMP"' EXIT

echo "→ fetching $SRC_URL"
if ! curl -fsSL --max-time 30 "$SRC_URL" -o "$TMP"; then
  echo "✗ download failed" >&2
  exit 1
fi

# Sanity check: models.dev returns a JSON object keyed by provider, each with a
# nested "models" map. Reject anything that isn't a JSON object or has no
# models at all, so a bad deploy can't silently empty the catalog.
if ! python3 - "$TMP" <<'PY'
import json, sys
with open(sys.argv[1]) as f:
    d = json.load(f)
if not isinstance(d, dict) or not d:
    sys.exit("not a non-empty JSON object")
total = sum(len(v.get("models", {})) for v in d.values() if isinstance(v, dict))
if total == 0:
    sys.exit("no models found")
print(f"  parsed ok: {len(d)} providers, {total} models")
PY
then
  echo "✗ verification failed (invalid JSON or no models)" >&2
  exit 1
fi

# No change? Nothing to do.
if [[ -f "$DEST" ]] && diff -q "$DEST" "$TMP" >/dev/null 2>&1; then
  echo "✓ already up to date"
  exit 0
fi

# Count priced models so the commit message is informative.
PRICED=$(python3 - "$TMP" <<'PY'
import json, sys
with open(sys.argv[1]) as f:
    d = json.load(f)
n = sum(1 for v in d.values() if isinstance(v, dict)
        for m in v.get("models", {}).values()
        if isinstance(m, dict) and m.get("cost"))
print(n)
PY
)

mv "$TMP" "$DEST"
echo "✓ wrote $DEST ($PRICED priced models)"

if [[ "${1:-}" == "--commit" ]]; then
  cd "$REPO_ROOT"
  git add "$DEST"
  if git diff --cached --quiet; then
    echo "✓ nothing staged (identical content)"
    exit 0
  fi
  git commit -m "chore(catalog): sync model pricing from models.dev

$PRICED priced models. Generated by scripts/sync-prices.sh"
  echo "✓ committed"
fi
